# Generated by Django 5.0.6 on 2024-07-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player1',
            field=models.CharField(default='Player 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player2',
            field=models.CharField(default='Player 2', max_length=100),
        ),
    ]
